"""esquema inicial

Revision ID: 23756a617f37
Revises: 
Create Date: 2026-08-17 12:59:49.836513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23756a617f37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_email', sa.String(length=150), nullable=True),
    sa.Column('entidad', sa.String(length=30), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=20), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_entidad'), 'auditoria', ['entidad'], unique=False)
    op.create_index(op.f('ix_auditoria_entidad_id'), 'auditoria', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_auditoria_fecha'), 'auditoria', ['fecha'], unique=False)
    op.create_index(op.f('ix_auditoria_id'), 'auditoria', ['id'], unique=False)
    op.create_table('consulta_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.String(length=300), nullable=True),
    sa.Column('encontrado', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consulta_log_fecha'), 'consulta_log', ['fecha'], unique=False)
    op.create_index(op.f('ix_consulta_log_id'), 'consulta_log', ['id'], unique=False)
    op.create_table('sedes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('nombre_corto', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('referencia', sa.Text(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('horario_atencion', sa.String(length=300), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('rampa', sa.Boolean(), nullable=True),
    sa.Column('ascensor', sa.Boolean(), nullable=True),
    sa.Column('banio_accesible', sa.Boolean(), nullable=True),
    sa.Column('estacionamiento_accesible', sa.Boolean(), nullable=True),
    sa.Column('personal_asistencia', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sedes_id'), 'sedes', ['id'], unique=False)
    op.create_index(op.f('ix_sedes_nombre'), 'sedes', ['nombre'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'gestor', 'validador', 'auditor', name='rol'), nullable=False),
    sa.Column('area', sa.String(length=150), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('edificios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('pisos', sa.Integer(), nullable=True),
    sa.Column('informacion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edificios_id'), 'edificios', ['id'], unique=False)
    op.create_index(op.f('ix_edificios_sede_id'), 'edificios', ['sede_id'], unique=False)
    op.create_table('dependencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('nombre_normalizado', sa.String(length=200), nullable=True),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('edificio_id', sa.Integer(), nullable=True),
    sa.Column('piso', sa.String(length=30), nullable=True),
    sa.Column('oficina', sa.String(length=50), nullable=True),
    sa.Column('horario', sa.String(length=300), nullable=True),
    sa.Column('servicios', sa.Text(), nullable=True),
    sa.Column('requisitos', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('rampa', sa.Boolean(), nullable=True),
    sa.Column('ascensor', sa.Boolean(), nullable=True),
    sa.Column('banio_accesible', sa.Boolean(), nullable=True),
    sa.Column('ruta_accesible', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('area', sa.String(length=150), nullable=True),
    sa.Column('responsable_validar', sa.String(length=200), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['edificio_id'], ['edificios.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependencias_area'), 'dependencias', ['area'], unique=False)
    op.create_index(op.f('ix_dependencias_estado'), 'dependencias', ['estado'], unique=False)
    op.create_index(op.f('ix_dependencias_id'), 'dependencias', ['id'], unique=False)
    op.create_index(op.f('ix_dependencias_nombre_normalizado'), 'dependencias', ['nombre_normalizado'], unique=False)
    op.create_index(op.f('ix_dependencias_sede_id'), 'dependencias', ['sede_id'], unique=False)
    op.create_index(op.f('ix_dependencias_tipo'), 'dependencias', ['tipo'], unique=False)
    op.create_table('alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dependencia_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('alias_normalizado', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['dependencia_id'], ['dependencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alias_alias_normalizado'), 'alias', ['alias_normalizado'], unique=False)
    op.create_index(op.f('ix_alias_dependencia_id'), 'alias', ['dependencia_id'], unique=False)
    op.create_index(op.f('ix_alias_id'), 'alias', ['id'], unique=False)
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dependencia_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('requisitos', sa.Text(), nullable=True),
    sa.Column('canal', sa.String(length=50), nullable=True),
    sa.Column('horario', sa.String(length=300), nullable=True),
    sa.Column('costo', sa.String(length=100), nullable=True),
    sa.Column('duracion_estimada', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dependencia_id'], ['dependencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicios_dependencia_id'), 'servicios', ['dependencia_id'], unique=False)
    op.create_index(op.f('ix_servicios_id'), 'servicios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servicios_id'), table_name='servicios')
    op.drop_index(op.f('ix_servicios_dependencia_id'), table_name='servicios')
    op.drop_table('servicios')
    op.drop_index(op.f('ix_alias_id'), table_name='alias')
    op.drop_index(op.f('ix_alias_dependencia_id'), table_name='alias')
    op.drop_index(op.f('ix_alias_alias_normalizado'), table_name='alias')
    op.drop_table('alias')
    op.drop_index(op.f('ix_dependencias_tipo'), table_name='dependencias')
    op.drop_index(op.f('ix_dependencias_sede_id'), table_name='dependencias')
    op.drop_index(op.f('ix_dependencias_nombre_normalizado'), table_name='dependencias')
    op.drop_index(op.f('ix_dependencias_id'), table_name='dependencias')
    op.drop_index(op.f('ix_dependencias_estado'), table_name='dependencias')
    op.drop_index(op.f('ix_dependencias_area'), table_name='dependencias')
    op.drop_table('dependencias')
    op.drop_index(op.f('ix_edificios_sede_id'), table_name='edificios')
    op.drop_index(op.f('ix_edificios_id'), table_name='edificios')
    op.drop_table('edificios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_sedes_nombre'), table_name='sedes')
    op.drop_index(op.f('ix_sedes_id'), table_name='sedes')
    op.drop_table('sedes')
    op.drop_index(op.f('ix_consulta_log_id'), table_name='consulta_log')
    op.drop_index(op.f('ix_consulta_log_fecha'), table_name='consulta_log')
    op.drop_table('consulta_log')
    op.drop_index(op.f('ix_auditoria_id'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_fecha'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_entidad_id'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_entidad'), table_name='auditoria')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
