"""agrega satisfaccion a consulta_log

Revision ID: c1bae2d4ea7a
Revises: 23756a617f37
Create Date: 2026-08-17 13:46:43.961632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1bae2d4ea7a'
down_revision: Union[str, Sequence[str], None] = '23756a617f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consulta_log', sa.Column('satisfaccion', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consulta_log', 'satisfaccion')
    # ### end Alembic commands ###
